export const SKY_CHARGE_DURATION = 600;
export const PRE_GLOW_DURATION = 800;
export const STRIKE_DURATION = 1300;
export const AFTERGLOW_DURATION = 700;
export const TOTAL_EVENT_DURATION = SKY_CHARGE_DURATION + PRE_GLOW_DURATION + STRIKE_DURATION + AFTERGLOW_DURATION;

export const LIGHTNING_MIN_INTERVAL = 20000;
export const LIGHTNING_MAX_INTERVAL = 30000;

export const WIND_CHANGE_MIN = 6000;
export const WIND_CHANGE_MAX = 14000;

export const LIGHTNING_CORE_WIDTH = 2;
export const LIGHTNING_GLOW_WIDTH = 8;
export const LIGHTNING_OUTER_BLUR = 45;
export const LIGHTNING_BRANCH_GLOW = 14;

export const MOBILE_BREAKPOINT = 500;
export const TABLET_BREAKPOINT = 768;
export const DESKTOP_BREAKPOINT = 1024;
